# Generated by Django 3.1.3 on 2021-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200831_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='content',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
